"""
orchestrator/bridge/upstox_client.py
──────────────────────────────────────
Fetches live holdings from Upstox API v2.

TOKEN MECHANISM — reads UPSTOX_TOKEN env var.
This token is generated by Engine 2's refresh_upstox_token.yml
(runs daily 7:30 AM IST via TOTP auto-login) and pushed into this
repo's GitHub secrets by scripts/push_upstox_token.py.

We do NOT replicate TOTP login. Engine 2 owns token generation.
We only consume UPSTOX_TOKEN that Engine 2 already manages.

Holdings endpoint mirrors Engine 2's portfolio.py exactly:
  GET /v2/portfolio/long-term-holdings
  Authorization: Bearer {UPSTOX_TOKEN}
  tradingsymbol normalised to SYMBOL.NS format.
"""

import json
import logging
import os
from datetime import datetime
from pathlib import Path

import requests

log = logging.getLogger("upstox_client")


def _token() -> str:
    token = os.environ.get("UPSTOX_TOKEN", "").strip()
    if not token:
        raise EnvironmentError(
            "UPSTOX_TOKEN not set. This is pushed daily by Engine 2's "
            "refresh_upstox_token.yml via scripts/push_upstox_token.py."
        )
    return token


def fetch_holdings() -> list[dict]:
    """
    Fetch long-term holdings. Mirrors Engine 2's portfolio.get_portfolio_details().
    Returns list of dicts with ticker, quantity, avg_cost_price, last_price,
    current_value, pnl, pnl_pct, exchange.
    """
    url  = "https://api.upstox.com/v2/portfolio/long-term-holdings"
    resp = requests.get(url, headers={
        "Authorization": f"Bearer {_token()}",
        "Accept": "application/json",
    }, timeout=30)

    if resp.status_code == 401:
        raise ValueError("UPSTOX_TOKEN expired (401). Engine 2 token push may not have run today.")
    resp.raise_for_status()

    holdings = []
    for item in resp.json().get("data", []):
        symbol = item.get("tradingsymbol", "")
        ticker = f"{symbol}.NS" if not symbol.endswith(".NS") else symbol
        qty    = float(item.get("quantity", 0))
        avg    = float(item.get("average_price", 0))
        ltp    = float(item.get("last_price", 0))
        if qty <= 0:
            continue
        holdings.append({
            "ticker":         ticker,
            "isin":           item.get("isin", ""),
            "quantity":       qty,
            "avg_cost_price": round(avg, 2),
            "last_price":     round(ltp, 2),
            "current_value":  round(qty * ltp, 2),
            "pnl":            round((ltp - avg) * qty, 2),
            "pnl_pct":        round((ltp - avg) / avg * 100, 2) if avg else 0.0,
            "exchange":       item.get("exchange", "NSE"),
            "company_name":   item.get("company_name", symbol),
        })

    log.info(f"Fetched {len(holdings)} holdings from Upstox.")
    return holdings


def get_portfolio_snapshot() -> dict:
    holdings = fetch_holdings()
    return {
        "as_of":          datetime.now().isoformat(),
        "total_value":    round(sum(h["current_value"] for h in holdings), 2),
        "holdings":       holdings,
        "holdings_count": len(holdings),
    }


def save_snapshot(snapshot: dict, cache_dir: Path):
    cache_dir.mkdir(parents=True, exist_ok=True)
    path = cache_dir / f"holdings_{datetime.now().strftime('%Y%m%d')}.json"
    with open(path, "w") as f:
        json.dump(snapshot, f, indent=2, default=str)
    log.info(f"Holdings cached: {path}")


def load_snapshot(cache_dir: Path) -> dict | None:
    files = sorted(cache_dir.glob("holdings_*.json"), reverse=True)
    if files:
        with open(files[0]) as f:
            return json.load(f)
    return None
